package com.example.demo.dao;

import com.example.demo.dataobject.CaseDO;
import com.example.demo.dataobject.InterfaceDO;

import java.util.List;

public interface CaseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_case
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_case
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    int insert(CaseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_case
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    int insertSelective(CaseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_case
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    CaseDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_case
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    int updateByPrimaryKeySelective(CaseDO record);
    int updateStatusAndResult(CaseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_case
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    int updateByPrimaryKey(CaseDO record);

    List<CaseDO> listCase();

    InterfaceDO selectByInterfaceId(Integer interfaceId);

    List<CaseDO> selectByIdList(List apiList);
}