package com.example.demo.dao;

import com.example.demo.dataobject.interfaceDO;

public interface interfaceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 15:02:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 15:02:05 CST 2020
     */
    int insert(interfaceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 15:02:05 CST 2020
     */
    int insertSelective(interfaceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 15:02:05 CST 2020
     */
    interfaceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 15:02:05 CST 2020
     */
    int updateByPrimaryKeySelective(interfaceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 15:02:05 CST 2020
     */
    int updateByPrimaryKey(interfaceDO record);
}