package com.example.demo.dao;

import com.example.demo.dataobject.InterfaceDO;

import java.util.List;

public interface InterfaceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    int insert(InterfaceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    int insertSelective(InterfaceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    InterfaceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    int updateByPrimaryKeySelective(InterfaceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_interface
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    int updateByPrimaryKey(InterfaceDO record);

    List<InterfaceDO> listInterface();

    Integer selectUniqueInterface(String projectName,String moduleName,String interfaceName);
}