package com.example.demo.dao;

import com.example.demo.dataobject.UserDO;

import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jun 07 09:48:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jun 07 09:48:36 CST 2020
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jun 07 09:48:36 CST 2020
     */
    int insertSelective(UserDO record);

    List<UserDO> listUser();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jun 07 09:48:36 CST 2020
     */
    UserDO selectByPrimaryKey(Integer id);
    UserDO selectByUserName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jun 07 09:48:36 CST 2020
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sun Jun 07 09:48:36 CST 2020
     */
    int updateByPrimaryKey(UserDO record);
}