package com.example.demo.dao;

import com.example.demo.dataobject.VariableConfigDO;

import java.util.List;

public interface VariableConfigDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_variable_config
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_variable_config
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    int insert(VariableConfigDO record);

    int insertAndUpdate(VariableConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_variable_config
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    int insertSelective(VariableConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_variable_config
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    VariableConfigDO selectByPrimaryKey(Integer id);
    List<VariableConfigDO> selectByCollectionId(Integer collectionId);

    Integer selectIdByCollectionIdAndVariableName(VariableConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_variable_config
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    int updateByPrimaryKeySelective(VariableConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_variable_config
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(VariableConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_variable_config
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    int updateByPrimaryKey(VariableConfigDO record);
}