package com.example.demo.dataobject;

import lombok.Data;

@Data
public class CaseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.id
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.header_value
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private String headerValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.body_value
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private String bodyValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.variable_list
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private String variableList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.expect_list
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private String expectList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.result
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.status
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.case_type
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private String caseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.description
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_case.interface_id
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    private Integer interfaceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.id
     *
     * @return the value of tb_case.id
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.id
     *
     * @param id the value for tb_case.id
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.header_value
     *
     * @return the value of tb_case.header_value
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public String getHeaderValue() {
        return headerValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.header_value
     *
     * @param headerValue the value for tb_case.header_value
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setHeaderValue(String headerValue) {
        this.headerValue = headerValue == null ? null : headerValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.body_value
     *
     * @return the value of tb_case.body_value
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public String getBodyValue() {
        return bodyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.body_value
     *
     * @param bodyValue the value for tb_case.body_value
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setBodyValue(String bodyValue) {
        this.bodyValue = bodyValue == null ? null : bodyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.variable_list
     *
     * @return the value of tb_case.variable_list
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public String getVariableList() {
        return variableList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.variable_list
     *
     * @param variableList the value for tb_case.variable_list
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setVariableList(String variableList) {
        this.variableList = variableList == null ? null : variableList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.expect_list
     *
     * @return the value of tb_case.expect_list
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public String getExpectList() {
        return expectList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.expect_list
     *
     * @param expectList the value for tb_case.expect_list
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setExpectList(String expectList) {
        this.expectList = expectList == null ? null : expectList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.result
     *
     * @return the value of tb_case.result
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.result
     *
     * @param result the value for tb_case.result
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.status
     *
     * @return the value of tb_case.status
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.status
     *
     * @param status the value for tb_case.status
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.case_type
     *
     * @return the value of tb_case.case_type
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public String getCaseType() {
        return caseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.case_type
     *
     * @param caseType the value for tb_case.case_type
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setCaseType(String caseType) {
        this.caseType = caseType == null ? null : caseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.description
     *
     * @return the value of tb_case.description
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.description
     *
     * @param description the value for tb_case.description
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_case.interface_id
     *
     * @return the value of tb_case.interface_id
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_case.interface_id
     *
     * @param interfaceId the value for tb_case.interface_id
     *
     * @mbg.generated Sat Jul 11 09:49:13 CST 2020
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }
}