package com.example.demo.dataobject;

public class CollectionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.id
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.collection_name
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    private String collectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.case_list
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    private String caseList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.id
     *
     * @return the value of tb_collection.id
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.id
     *
     * @param id the value for tb_collection.id
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.collection_name
     *
     * @return the value of tb_collection.collection_name
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.collection_name
     *
     * @param collectionName the value for tb_collection.collection_name
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName == null ? null : collectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.case_list
     *
     * @return the value of tb_collection.case_list
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    public String getCaseList() {
        return caseList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.case_list
     *
     * @param caseList the value for tb_collection.case_list
     *
     * @mbg.generated Sat Jul 25 11:21:13 CST 2020
     */
    public void setCaseList(String caseList) {
        this.caseList = caseList == null ? null : caseList.trim();
    }
}