package com.example.demo.dataobject;

import lombok.Data;

import java.util.Date;

@Data
public class InterfaceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.id
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.project_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.module_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.interface_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private String interfaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.request_method
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private String requestMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.parameter_type
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private String parameterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.path
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.description
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_interface.modify_date
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.id
     *
     * @return the value of tb_interface.id
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.id
     *
     * @param id the value for tb_interface.id
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.project_name
     *
     * @return the value of tb_interface.project_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.project_name
     *
     * @param projectName the value for tb_interface.project_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.module_name
     *
     * @return the value of tb_interface.module_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.module_name
     *
     * @param moduleName the value for tb_interface.module_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.interface_name
     *
     * @return the value of tb_interface.interface_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.interface_name
     *
     * @param interfaceName the value for tb_interface.interface_name
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName == null ? null : interfaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.request_method
     *
     * @return the value of tb_interface.request_method
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public String getRequestMethod() {
        return requestMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.request_method
     *
     * @param requestMethod the value for tb_interface.request_method
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod == null ? null : requestMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.parameter_type
     *
     * @return the value of tb_interface.parameter_type
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public String getParameterType() {
        return parameterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.parameter_type
     *
     * @param parameterType the value for tb_interface.parameter_type
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setParameterType(String parameterType) {
        this.parameterType = parameterType == null ? null : parameterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.path
     *
     * @return the value of tb_interface.path
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.path
     *
     * @param path the value for tb_interface.path
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.description
     *
     * @return the value of tb_interface.description
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.description
     *
     * @param description the value for tb_interface.description
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_interface.modify_date
     *
     * @return the value of tb_interface.modify_date
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_interface.modify_date
     *
     * @param modifyDate the value for tb_interface.modify_date
     *
     * @mbg.generated Sun Jul 05 16:17:04 CST 2020
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}