package com.example.demo.dataobject;

public class ProjectDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_project.id
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_project.project_name
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_project.module_name
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_project.IP_address
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_project.description
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_project.id
     *
     * @return the value of tb_project.id
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_project.id
     *
     * @param id the value for tb_project.id
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_project.project_name
     *
     * @return the value of tb_project.project_name
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_project.project_name
     *
     * @param projectName the value for tb_project.project_name
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_project.module_name
     *
     * @return the value of tb_project.module_name
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_project.module_name
     *
     * @param moduleName the value for tb_project.module_name
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_project.IP_address
     *
     * @return the value of tb_project.IP_address
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_project.IP_address
     *
     * @param ipAddress the value for tb_project.IP_address
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_project.description
     *
     * @return the value of tb_project.description
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_project.description
     *
     * @param description the value for tb_project.description
     *
     * @mbg.generated Fri Jun 26 20:00:44 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}