package com.example.demo.dataobject;

import lombok.Data;

@Data
public class VariableConfigDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_variable_config.id
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_variable_config.variable_name
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    private String variableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_variable_config.collection_id
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    private Integer collectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_variable_config.variable_value
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    private String variableValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_variable_config.id
     *
     * @return the value of tb_variable_config.id
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_variable_config.id
     *
     * @param id the value for tb_variable_config.id
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_variable_config.variable_name
     *
     * @return the value of tb_variable_config.variable_name
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public String getVariableName() {
        return variableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_variable_config.variable_name
     *
     * @param variableName the value for tb_variable_config.variable_name
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public void setVariableName(String variableName) {
        this.variableName = variableName == null ? null : variableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_variable_config.collection_id
     *
     * @return the value of tb_variable_config.collection_id
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public Integer getCollectionId() {
        return collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_variable_config.collection_id
     *
     * @param collectionId the value for tb_variable_config.collection_id
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public void setCollectionId(Integer collectionId) {
        this.collectionId = collectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_variable_config.variable_value
     *
     * @return the value of tb_variable_config.variable_value
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public String getVariableValue() {
        return variableValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_variable_config.variable_value
     *
     * @param variableValue the value for tb_variable_config.variable_value
     *
     * @mbg.generated Thu Jul 23 21:35:11 CST 2020
     */
    public void setVariableValue(String variableValue) {
        this.variableValue = variableValue == null ? null : variableValue.trim();
    }
}